language: ruby
rvm:
  - 2.3.3

sudo: false

branches:
  only:
  - master
  - travis

before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

script:
  - sh build.sh

after_success:
  - sh publish.sh
