# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-archives

# Site settings
title: "Building Kidfund"
description: > # this means to ignore newlines until "email:"
   Code | Design | Product

email: info@kidfund.us
#blog logo
logo: "/assets/images/kidfund_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Kidfund'
main_site_url: 'http://www.kidfund.us'
author: 'Tim Broder'
author_image: "/assets/images/author_timbroder.jpeg"

permalink: /:year/:month/:day/:title.html
paginate:	10

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@kidfund'

jekyll-archives:
  enabled: all
  layout: 'category'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-73689903-5

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/kidfund
    desc:	Fork us on github
  - icon:	twitter
    url:	https://twitter.com/kidfund
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/Kidfund
    desc: Follow us on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	instagram
    url:	https://www.instagram.com/kidfund/
    desc:	Check us out on Instagram
    share_url:
    share_title:
    share_link:
